site_name: mtcli-risco
site_description: Plugin de controle de risco para o mtcli
site_author: Valmir França da Silva
site_url: https://mtcli-risco.readthedocs.io

repo_name: vfranca/mtcli-risco
repo_url: https://github.com/vfranca/mtcli-risco
edit_uri: ""

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.annotate
    - toc.integrate

nav:
  - Início: index.md
  - Como usar: usage.md
  - API Interna: api.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
